name: compromised action
author: bdunahu
description: tries to look innocent

input:
        who-to-greet:
                description: Who to greet
                required: true
                default: World

outputs:
        time:
                description: The time we greeted you

runs:
        using: node20
        main: dist/index.js